{
  "contest": 271,
  "handle": "debo",
  "risk": "2",
  "title": "[M-02] Denial of Service on failed call Dos",
  "issueId": 127,
  "issueUrl": "https://github.com/code-423n4/2023-08-pooltogether-findings/issues/127"
}